"""initial migration

Revision ID: 1f63ca8d27c7
Revises: 
Create Date: 2024-10-04 12:44:56.223518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f63ca8d27c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('interval_s', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('ugz_intern', 'innet', 'meteoblue', name='provider'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wgs84_lat', sa.Float(), nullable=False),
    sa.Column('wgs84_lon', sa.Float(), nullable=False),
    sa.Column('masl', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_serial', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('logger_id', sa.Integer(), nullable=False),
    sa.Column('technician', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logger_id'], ['loggers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logger_id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type', sa.Enum('wind_speed_ms', 'east_wind_speed_ms', 'wind_speed_max_ms', 'humidity_pct', 'north_wind_speed_ms', 'irradiation_wm2', 'wind_direction_deg', 'pressure_hpa', 'temperature_c', 'battery_voltage_v', name='measurementtype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.ForeignKeyConstraint(['logger_id'], ['loggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('installations')
    op.drop_table('loggers')
    op.drop_table('sites')
    op.drop_table('models')
    # ### end Alembic commands ###
