"""add unique key to tables

Revision ID: b44a2e2c5e20
Revises: 1f63ca8d27c7
Create Date: 2024-10-04 16:09:40.010386

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b44a2e2c5e20"
down_revision = "1f63ca8d27c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("loggers", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["sensor_id"])
        batch_op.create_unique_constraint(None, ["sensor_serial"])

    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("loggers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
